import math
print ("Ingrese su número")
numero = float(input())
seno = math.sin(numero)
coseno = math.cos(numero)
tangente = math.tan(numero)
raiz_cuadrada = math.sqrt(numero)
logaritmo_natural = math.log(numero)
logaritmo_base10 = math.log10(numero)
print ("Del número ", str(numero))
print ("Su seno es: ", str(seno))
print ("Su coseno es: ", str(coseno))
print ("Su tangente es: ", str(tangente))
print ("Su raíz cuadrada es: ", str(raiz_cuadrada))
print ("Su logaritmo natural es: ", str(logaritmo_natural))
print ("Su logaritmo base 10 es: ", str(logaritmo_base10))